server:
  port: 5001

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git: # 远程仓库的git地址
          uri: https://github.com/zhanghujia/spring-cloud-config.git